// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdY_RtbTzYZ41FTxTrYfJWFn0_sOe-Ifk',
    appId: '1:534925692790:web:9c3bd147aad3f73063b457',
    messagingSenderId: '534925692790',
    projectId: 'agenda-8d59b',
    authDomain: 'agenda-8d59b.firebaseapp.com',
    storageBucket: 'agenda-8d59b.firebasestorage.app',
    measurementId: 'G-WZD81V1G9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7GbC3wEQFWSXBWS5Cw0UjahI2PkBAOCg',
    appId: '1:534925692790:android:014a8dffb82b89e263b457',
    messagingSenderId: '534925692790',
    projectId: 'agenda-8d59b',
    storageBucket: 'agenda-8d59b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDhPcBlUL8yG_Eey3kO0h7vaNOfZEdPGU',
    appId: '1:534925692790:ios:cc659854c62c59fb63b457',
    messagingSenderId: '534925692790',
    projectId: 'agenda-8d59b',
    storageBucket: 'agenda-8d59b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationAgenda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDhPcBlUL8yG_Eey3kO0h7vaNOfZEdPGU',
    appId: '1:534925692790:ios:cc659854c62c59fb63b457',
    messagingSenderId: '534925692790',
    projectId: 'agenda-8d59b',
    storageBucket: 'agenda-8d59b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationAgenda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdY_RtbTzYZ41FTxTrYfJWFn0_sOe-Ifk',
    appId: '1:534925692790:web:328a2c9a38a0487d63b457',
    messagingSenderId: '534925692790',
    projectId: 'agenda-8d59b',
    authDomain: 'agenda-8d59b.firebaseapp.com',
    storageBucket: 'agenda-8d59b.firebasestorage.app',
    measurementId: 'G-GHH3X7E2MR',
  );
}
